version: "3.9"

services:
  epoch-service:
    build: ./services/epoch-service
    container_name: epoch-service
    ports:
      - "8081:8081"
    command: python -m app.main
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/epoch"]
      interval: 5s
      timeout: 3s
      retries: 10

  now-time-service:
    build: ./services/now-time-service
    container_name: now-time-service
    ports:
      - "8080:8080"
    environment:
      - EPOCH_BASEURL=http://epoch-service:8081
    depends_on:
      epoch-service:
        condition: service_healthy